// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8CYaLLR4Jy_iPinAyE3CYqHQWphjmJEU',
    appId: '1:820535920295:android:7b0c3440649234d44c7d82',
    messagingSenderId: '820535920295',
    projectId: 'ytnkio-b9f02',
    storageBucket: 'ytnkio-b9f02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4oRbaDmJLd5N1BEaM4UYYnZ2FRKHZUGE',
    appId: '1:820535920295:ios:185340c245ee7e214c7d82',
    messagingSenderId: '820535920295',
    projectId: 'ytnkio-b9f02',
    storageBucket: 'ytnkio-b9f02.firebasestorage.app',
    androidClientId:
        '820535920295-s80dqho5b16ku88jdhj4n7niv63j4d55.apps.googleusercontent.com',
    iosClientId:
        '820535920295-fc32rdocdesvbe0090hl41stsdclshn7.apps.googleusercontent.com',
    iosBundleId: 'com.ytnkio.talentapp',
  );
}
